spring.application.name=Chemiki

# App specific
app.email.from=noreply@chemiki.com


# application.properties
spring.web.resources.static-locations=classpath:/static/
# ----------------------------



logging.level.org.springframework=INFO
# Set your base package to debug (adjust based on your package)
logging.level.com.example=DEBUG

# ----------------------------
# Spring Security (Optional for JWT-based systems)
# ----------------------------
# Default user (only needed if you're using basic auth for testing)
spring.security.user.name=admin
# Default password
spring.security.user.password=admin