spring.application.name=Chemiki

# ----------------------------
# Email Configuration
# ----------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tiwariabishek44@gmail.com
spring.mail.password=yren tbfv wcie ccko
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App specific
app.email.from=noreply@chemiki.com

# ----------------------------
# Static Resources Configuration
# ----------------------------
spring.web.resources.static-locations=classpath:/static/

# ----------------------------
# JWT Configuration
# ----------------------------
# 1 day in milliseconds
jwt.accessTokenExpiration=86400000
# 1 minute in milliseconds
jwt.otpTokenExpiration=60000
# 7 days in milliseconds
jwt.refreshTokenExpiration=604800000
# Secret key used to sign the JWT (you should override this in production)
jwt.secret=hVR7mKT9FtH6FQ63yU1ZVZKy+F5q3V5MXlBp8b9MOLg=

# ----------------------------
# Server Configuration
# ----------------------------
server.port=8080

# ----------------------------
# Logging Configuration
# ----------------------------
# Set log level for Spring
logging.level.org.springframework=INFO
# Set your base package to debug (adjust based on your package)
logging.level.com.example=DEBUG